before_script:
  - "sh -e /etc/init.d/xvfb start"
  #- "cp config/database.yml.mysql.jruby config/database.yml"
  - "if [[ `eval ruby -v` =~ 'jruby' ]]; then database_yml=config/database.yml.$db.jruby; else database_yml=config/database.yml.$db; fi;echo $database_yml;cp $database_yml config/database.yml;"
  - "bundle exec rake db:create db:migrate db:test:clone > /dev/null"
script:
  - "DISPLAY=:99.0 bundle exec rspec ./spec/"
  - "DISPLAY=:99.0 bundle exec cucumber"
notifications:
  email:
    - josh@isotope11.com
    - agamble@isotope11.com
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby

env:
  - db=mysql
  - db=postgres
